spring:
  datasource:
    one:
      url: jdbc:mysql://localhost:3306/mysql_emoji_test
      username: root
      password: 123456
    two:
      url: jdbc:mysql://localhost:3306/mysql_emoji_test
      username: root
      password: 123456
    three:
      url: jdbc:mysql://localhost:3306/mysql_emoji_test
      username: root
      password: 123456

