spring:
  datasource:
    one:
      url: jdbc:mysql://localhost:3306/mysql_emoji_test
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    two:
      url: jdbc:mysql://localhost:3306/mysql_emoji_test
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
    three:
      url: jdbc:mysql://localhost:3306/mysql_emoji_test
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource

